image: gitpod/workspace-full

tasks:
  - before: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform

  - init: go get && go build ./... && go test ./... && make
    command: make install

vscode:
  extensions:
    - golang.go
    - hashicorp.terraform
